version: "2.4"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ".env"
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '127.0.0.1:6379:6379'

volumes:
  postgres-data:
    external: true
