version: "2.4"
services:
  postgis:
    container_name: postgis
    image: postgis/postgis
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres-data:
    external: true
