version: "2.4"
services:
  postgis:
    container_name: postgis
    image: postgis/postgis
    restart: always
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - "/opt/sportaj.ga/data/db:/var/lib/postgresql/data"

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
